### ISSUE TITLE
turkish characters problem

### ISSUE THREAD

**Issue by turgay23** [CompassSecurity/burp-copy-request-response#9]
When using the full + full copy feature, some Turkish characters are corrupted, can you fix this? thanks.

burp version : Community 2023.5.4
jython-standalone-2.7.3.jar installed.
OS: win11

response body

{
    "pk": "123123123",
    "user_id": "12323443534634",
    "text": "Tekerleğine bak",
    "type": 0,
    "created_at": 1687250879,
    "created_at_utc": 1687250879
}

Copy HTTP Request & Response (Full/Full)

open txt file and paste this

final

{
    "pk": "123123123",
    "user_id": "12323443534634",
    "text": "TekerleÄŸine bak",
    "type": 0,
    "created_at": 1687250879,
    "created_at_utc": 1687250879
}

turkish "ğ" is changed " Ä "

**Comment by turgay23** [comment]
Hello again. I simply wrote the code that only copies the body part. but I still could not solve the Turkish character problem. where am i doing wrong?

https://github.com/turgay23/copyresponsebody/blob/main/copyresponsebody.py

**Comment by emanuelduss** [comment]
Hi turgay23

You can use UTF-8 encoding to fix this.

It's fixed in the latest version.

This is the fix: https://github.com/CompassSecurity/burp-copy-request-response/commit/7f1f707bc7dafc16d0a0a75064c5ca6ca64d3228

Best,
Emanuel
